version: '3.8'

services:
  app:
    build: .
    container_name: spring-boot-starter
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    networks:
      - spring-network

  # Uncomment to add a database
  # db:
  #   image: postgres:14-alpine
  #   container_name: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=starter_db
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - spring-network

networks:
  spring-network:
    driver: bridge

# Uncomment if using database
# volumes:
#   postgres-data: