CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "first_name" varchar(255),
  "last_name" varchar(255),
  "password" varchar(255) NOT NULL,
  "cgu_date" date,
  "is_activated" boolean NOT NULL,
  "created_at" datetime(6) NOT NULL DEFAULT (CURRENT_TIMESTAMP(6)),
  "updated_at" datetime(6) NOT NULL DEFAULT (CURRENT_TIMESTAMP(6)),
  "role" "enum(USER,ADMIN)" NOT NULL DEFAULT 'USER'
);

CREATE TABLE "list" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "user_id" int NOT NULL,
  "is_shared" boolean NOT NULL DEFAULT false
);

CREATE TABLE "list_share" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "list_id" int NOT NULL,
  "shared_with_user_id" int NOT NULL
);

CREATE TABLE "person" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "age" int NOT NULL,
  "french_level" int NOT NULL,
  "gender" "enum(FEMALE,MALE,OTHER)" NOT NULL,
  "name" varchar(50) NOT NULL,
  "old_dwwm" boolean NOT NULL,
  "profile" "enum(A_LAISE,RESERVE,TIMIDE)" NOT NULL,
  "tech_level" int NOT NULL,
  "list_id" int NOT NULL
);

CREATE TABLE "draw" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" datetime(6),
  "list_id" int NOT NULL,
  "title" varchar(255)
);

CREATE TABLE "group" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "draw_id" int NOT NULL
);

CREATE TABLE "group_person" (
  "group_id" int NOT NULL,
  "person_id" int NOT NULL
);

CREATE UNIQUE INDEX ON "list" ("name", "user_id");

CREATE UNIQUE INDEX ON "list_share" ("list_id", "shared_with_user_id");

COMMENT ON TABLE "user" IS 'Compte utilisateur';

COMMENT ON TABLE "list" IS 'Listes de personnes par utilisateur';

COMMENT ON TABLE "list_share" IS 'Partage de listes entre utilisateurs';

COMMENT ON TABLE "person" IS 'Personne appartenant à une liste';

COMMENT ON TABLE "draw" IS 'Tirage de groupes depuis une liste';

COMMENT ON TABLE "group" IS 'Groupe créé lors d’un tirage';

COMMENT ON TABLE "group_person" IS 'Association entre un groupe et ses membres';

ALTER TABLE "list" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "list_share" ADD FOREIGN KEY ("list_id") REFERENCES "list" ("id");

ALTER TABLE "list_share" ADD FOREIGN KEY ("shared_with_user_id") REFERENCES "user" ("id");

ALTER TABLE "person" ADD FOREIGN KEY ("list_id") REFERENCES "list" ("id");

ALTER TABLE "draw" ADD FOREIGN KEY ("list_id") REFERENCES "list" ("id");

ALTER TABLE "group" ADD FOREIGN KEY ("draw_id") REFERENCES "draw" ("id");

ALTER TABLE "group_person" ADD FOREIGN KEY ("group_id") REFERENCES "group" ("id");

ALTER TABLE "group_person" ADD FOREIGN KEY ("person_id") REFERENCES "person" ("id");
