name: Deploy EasyGroup-Interpromo to Production

on:
  push:
    branches:
      - deploy-rasp

jobs:
  production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build backend (tests inclus)
        run: mvn --batch-mode --quiet install -Dspring.profiles.active=test -DskipTests=false

      - name: Setup Tailscale (OAuth)
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no pi@raspberrypi.tail06bcb8.ts.net "echo '✅ SSH OK'"

      - name: Deploy to production via Tailscale SSH
        run: |
          ssh -o StrictHostKeyChecking=no pi@raspberrypi.tail06bcb8.ts.net "
            cd brief-26 &&
            git pull origin deploy-rasp &&
            docker compose -f docker-compose.rasp.yml --env-file .env --project-name easygroup-inter-prod up --build -d
          "
